### ISSUE TITLE
Création d'un deuxieme QRCode qui renvoi vers le ticket si on est connecté

### ISSUE THREAD

**Issue by lmag** [Evarisk/gmao#20]
- [x] Activer l'Interface standard des tickets de Dolibarr
- [ ] Création d'une interface publique pour les techniciens (a voir plus tard surement)
- [x] Création de la génération d'un QR-Code qui renvoie vers l'url interne des tickets
- [x] Génération de l'impression de l'etiquette pour les techniciens internes

**Comment by lmag** [comment]
Ticket Client : https://demodoli.digirisk.com/htdocs/public/ticket/index.php?entity=1
Avec les informations de consultation (mail + Sha ticket)
Ticket Technicien : https://demodoli.digirisk.com/htdocs/ticket/card.php?id=2

- [x] Model odt 1
- [x] Model odt 2
- [x] Model odt1+ odt 2 (avec un saut de page)

**Comment by evarisk-charles** [comment]
- [x] garder le concept de la creation du qr code dans le build doc cependant on doit l'améliorer avec une fonction spéciale 
- [x] modif sha_ticket par object_track_id et mettre thirdparty_email au lieu de ticket_email pour les clé de l'odt dans tmparray

- [x] Mettre les étiquettes à la verticale
- [x] Changer le modèle 1 + 2 en ticket client et ticket interne => remplace le mot document de maintenance

- [ ] Rajouter dans le paramètre le fait que le QR Code puisse faire de l'auto login
Modif pour mettre l'id sur 8 au lieu de 16

- [x] Le ticket de maintenance doit aller sur le ticket/card .php
